# Generated by Django 3.2.13 on 2023-04-19 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interfaces', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interface',
            old_name='interface_name',
            new_name='name',
        ),
    ]
