# Generated by Django 3.2.13 on 2022-07-06 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interface',
            options={'verbose_name': '接口测试', 'verbose_name_plural': '接口测试'},
        ),
        migrations.RenameField(
            model_name='projects',
            old_name='programer',
            new_name='programmer',
        ),
        migrations.RenameField(
            model_name='projects',
            old_name='publist_app',
            new_name='publish_app',
        ),
    ]
