# Generated by Django 3.2.14 on 2022-10-18 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bug',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now_add=True, help_text='更新时间', verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, help_text='逻辑删除', verbose_name='逻辑删除')),
                ('id', models.AutoField(help_text='id主键', primary_key=True, serialize=False, verbose_name='id主键')),
                ('project_id', models.CharField(help_text='项目id', max_length=20, verbose_name='项目id')),
                ('bug_id', models.IntegerField(help_text='缺陷id', max_length=50, verbose_name='缺陷id')),
                ('bug', models.JSONField(help_text='缺陷原始信息', verbose_name='缺陷原始信息')),
                ('time', models.DateTimeField(help_text='查询', verbose_name='查询时间')),
                ('isread', models.CharField(help_text='是否读取', max_length=10, verbose_name='是否读取')),
            ],
            options={
                'verbose_name': 'BUG原始信息',
                'verbose_name_plural': 'BUG原始信息',
                'db_table': 'tbl_bug',
            },
        ),
        migrations.CreateModel(
            name='BUG_Status',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now_add=True, help_text='更新时间', verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, help_text='逻辑删除', verbose_name='逻辑删除')),
                ('id', models.AutoField(help_text='id主键', primary_key=True, serialize=False, verbose_name='id主键')),
                ('project_id', models.CharField(help_text='项目id', max_length=20, verbose_name='项目id')),
                ('project_name', models.CharField(help_text='项目名称', max_length=100, verbose_name='项目名称')),
                ('unresolved_bug', models.CharField(help_text='未解决BUG', max_length=20, verbose_name='未解决BUG')),
                ('toclosed_bug', models.CharField(help_text='待关闭BUG', max_length=20, verbose_name='待关闭BUG')),
                ('send_status', models.CharField(help_text='发送状态', max_length=10, verbose_name='发送状态')),
                ('send_time', models.DateTimeField(help_text='发送时间', verbose_name='发送时间')),
                ('query_time', models.DateTimeField(help_text='查询时间', verbose_name='查询时间')),
                ('account', models.CharField(help_text='操作用户', max_length=50, verbose_name='操作用户')),
                ('severity_one', models.IntegerField(help_text='严重等级-一级', max_length=10, verbose_name='严重等级-一级')),
                ('severity_two', models.IntegerField(help_text='严重等级-二级', max_length=10, verbose_name='严重等级-二级')),
                ('severity_three', models.IntegerField(help_text='严重等级-三级', max_length=10, verbose_name='严重等级-三级')),
                ('severity_four', models.IntegerField(help_text='严重等级-四级', max_length=10, verbose_name='严重等级-四级')),
                ('assignedTo', models.CharField(help_text='指派人', max_length=20, verbose_name='指派人')),
                ('severity_one_title', models.CharField(help_text='严重等级一级BUG标题', max_length=500, verbose_name='严重等级一级BUG标题')),
                ('severity_one_url', models.CharField(help_text='严重等级一级BUGURL', max_length=500, verbose_name='严重等级一级BUGURL')),
            ],
            options={
                'verbose_name': 'BUG状态信息',
                'verbose_name_plural': 'BUG状态信息',
                'db_table': 'tbl_bug_status',
            },
        ),
    ]
