# Generated by Django 3.2.14 on 2023-02-07 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bug_id', models.IntegerField(help_text='缺陷ID', verbose_name='缺陷ID')),
                ('project_id', models.IntegerField(help_text='项目ID', verbose_name='项目ID')),
                ('bug', models.JSONField(help_text='缺陷原始信息', verbose_name='缺陷原始信息')),
                ('status', models.CharField(help_text='是否解决', max_length=10, verbose_name='是否解决')),
            ],
            options={
                'verbose_name': '禅道保存的未解决BUG',
                'verbose_name_plural': '禅道保存的未解决BUG',
                'db_table': 'zentao_bug',
            },
        ),
        migrations.CreateModel(
            name='BugPersonnelConfig',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now_add=True, help_text='更新时间', verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, help_text='逻辑删除', verbose_name='逻辑删除')),
                ('id', models.AutoField(help_text='ID主键', primary_key=True, serialize=False, verbose_name='ID主键')),
                ('spell', models.CharField(help_text='拼音', max_length=50, verbose_name='拼音')),
                ('name', models.CharField(help_text='姓名', max_length=50, verbose_name='姓名')),
                ('phone', models.CharField(help_text='手机号', max_length=50, verbose_name='手机号')),
            ],
            options={
                'verbose_name': '人员信息拼音对照',
                'verbose_name_plural': '人员信息拼音对照',
                'db_table': 'zentao_bug_personnel_config',
            },
        ),
        migrations.CreateModel(
            name='BugProjectConfig',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now_add=True, help_text='更新时间', verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, help_text='逻辑删除', verbose_name='逻辑删除')),
                ('project_id', models.CharField(help_text='项目ID', max_length=50, primary_key=True, serialize=False, verbose_name='项目ID')),
                ('project_name', models.CharField(help_text='项目名称', max_length=100, verbose_name='项目名称')),
                ('qywx_webhook', models.CharField(blank=True, help_text='企业微信webhook推送地址', max_length=500, verbose_name='企业微信webhook推送地址')),
                ('status', models.CharField(help_text='推送状态', max_length=10, verbose_name='是否推送状态')),
            ],
            options={
                'verbose_name': '禅道项目推送消息相关配置',
                'verbose_name_plural': '禅道项目推送消息相关配置',
                'db_table': 'zentao_project_config',
            },
        ),
        migrations.CreateModel(
            name='ZentaoConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now_add=True, help_text='更新时间', verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, help_text='逻辑删除', verbose_name='逻辑删除')),
                ('url', models.CharField(help_text='禅道登录地址', max_length=500, verbose_name='禅道登录地址')),
            ],
            options={
                'verbose_name': '禅道登录地址配置信息',
                'verbose_name_plural': '禅道登录地址配置信息',
                'db_table': 'zentao_url_config',
            },
        ),
        migrations.CreateModel(
            name='ZentaoUserConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now_add=True, help_text='更新时间', verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, help_text='逻辑删除', verbose_name='逻辑删除')),
                ('account', models.CharField(help_text='账号', max_length=50, verbose_name='账号')),
                ('password', models.CharField(help_text='密码', max_length=50, verbose_name='密码')),
                ('zentaosid', models.CharField(default='', help_text='ZentaoSid', max_length=200, verbose_name='ZentaoSid')),
                ('enable', models.IntegerField(default=0, help_text='是否启用', verbose_name='是否启用')),
            ],
            options={
                'verbose_name': '登录禅道账号相关配置信息',
                'verbose_name_plural': '登录禅道账号相关配置信息',
                'db_table': 'zentao_login_user_config',
            },
        ),
    ]
