# Generated by Django 3.2.14 on 2022-11-14 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BugPersonnelConfig',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now_add=True, help_text='更新时间', verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, help_text='逻辑删除', verbose_name='逻辑删除')),
                ('id', models.AutoField(help_text='ID主键', primary_key=True, serialize=False, verbose_name='ID主键')),
                ('spell', models.CharField(help_text='拼音', max_length=50, verbose_name='拼音')),
                ('name', models.CharField(help_text='姓名', max_length=50, verbose_name='姓名')),
                ('phone', models.IntegerField(help_text='手机号', verbose_name='手机号')),
            ],
            options={
                'verbose_name': 'BUG状态信息',
                'verbose_name_plural': 'BUG状态信息',
                'db_table': 'tbl_zentao_bug_personnel_config',
            },
        ),
        migrations.CreateModel(
            name='BugProjectConfig',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now_add=True, help_text='更新时间', verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, help_text='逻辑删除', verbose_name='逻辑删除')),
                ('project_id', models.CharField(help_text='项目ID', max_length=50, primary_key=True, serialize=False, verbose_name='项目ID')),
                ('project_name', models.CharField(help_text='项目名称', max_length=100, verbose_name='项目名称')),
                ('qywx_webhook', models.CharField(blank=True, help_text='企业微信webhook推送地址', max_length=500, verbose_name='企业微信webhook推送地址')),
                ('status', models.CharField(help_text='推送状态', max_length=10, verbose_name='是否推送状态')),
            ],
            options={
                'verbose_name': 'bug推送配置',
                'verbose_name_plural': 'bug推送配置',
                'db_table': 'tbl_zentao_bug_config',
            },
        ),
        migrations.CreateModel(
            name='ZentaoConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now_add=True, help_text='更新时间', verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, help_text='逻辑删除', verbose_name='逻辑删除')),
                ('url', models.CharField(help_text='禅道登录地址', max_length=500, verbose_name='禅道登录地址')),
            ],
            options={
                'verbose_name': '禅道配置信息',
                'verbose_name_plural': '禅道配置信息',
                'db_table': 'tbl_zentao_config',
            },
        ),
        migrations.CreateModel(
            name='ZentaoUserConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now_add=True, help_text='更新时间', verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, help_text='逻辑删除', verbose_name='逻辑删除')),
                ('account', models.CharField(help_text='账号', max_length=50, verbose_name='账号')),
                ('password', models.CharField(help_text='密码', max_length=50, verbose_name='密码')),
                ('zentaosid', models.CharField(default='', help_text='ZentaoSid', max_length=200, verbose_name='ZentaoSid')),
                ('enable', models.IntegerField(default=0, help_text='是否启用', verbose_name='是否启用')),
            ],
            options={
                'verbose_name': '禅道用户配置信息',
                'verbose_name_plural': '禅道用户配置信息',
                'db_table': 'tbl_zentao_user_config',
            },
        ),
        migrations.CreateModel(
            name='BugStatus',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now_add=True, help_text='更新时间', verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, help_text='逻辑删除', verbose_name='逻辑删除')),
                ('id', models.AutoField(help_text='id主键', primary_key=True, serialize=False, verbose_name='id主键')),
                ('unresolved_bug', models.CharField(help_text='未解决BUG', max_length=20, verbose_name='未解决BUG')),
                ('toclosed_bug', models.CharField(help_text='待关闭BUG', max_length=20, verbose_name='待关闭BUG')),
                ('send_status', models.CharField(help_text='发送状态', max_length=10, verbose_name='发送状态')),
                ('send_time', models.DateTimeField(help_text='发送时间', verbose_name='发送时间')),
                ('query_time', models.DateTimeField(help_text='查询时间', verbose_name='查询时间')),
                ('account', models.CharField(help_text='操作用户', max_length=50, verbose_name='操作用户')),
                ('severity_one', models.IntegerField(help_text='严重等级-一级', verbose_name='严重等级-一级')),
                ('severity_two', models.IntegerField(help_text='严重等级-二级', verbose_name='严重等级-二级')),
                ('severity_three', models.IntegerField(help_text='严重等级-三级', verbose_name='严重等级-三级')),
                ('severity_four', models.IntegerField(help_text='严重等级-四级', verbose_name='严重等级-四级')),
                ('assignedTo', models.CharField(help_text='指派人', max_length=20, verbose_name='指派人')),
                ('severity_one_title', models.CharField(help_text='严重等级一级BUG标题', max_length=500, verbose_name='严重等级一级BUG标题')),
                ('severity_one_url', models.CharField(help_text='严重等级一级BUGURL', max_length=500, verbose_name='严重等级一级BUGURL')),
                ('project_id', models.ForeignKey(blank=True, help_text='所属项目ID', on_delete=django.db.models.deletion.CASCADE, to='zentao.bugprojectconfig', verbose_name='所属项目ID')),
            ],
            options={
                'verbose_name': 'BUG状态信息',
                'verbose_name_plural': 'BUG状态信息',
                'db_table': 'tbl_zentao_bug_status',
            },
        ),
        migrations.CreateModel(
            name='Bug',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now_add=True, help_text='更新时间', verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, help_text='逻辑删除', verbose_name='逻辑删除')),
                ('id', models.AutoField(help_text='ID主键', primary_key=True, serialize=False, verbose_name='ID主键')),
                ('bug_id', models.IntegerField(help_text='缺陷id', verbose_name='缺陷id')),
                ('bug', models.JSONField(help_text='缺陷原始信息', verbose_name='缺陷原始信息')),
                ('isread', models.CharField(help_text='是否读取', max_length=10, verbose_name='是否读取')),
                ('project_id', models.ForeignKey(help_text='所属项目ID', on_delete=django.db.models.deletion.CASCADE, to='zentao.bugprojectconfig', verbose_name='所属项目ID')),
            ],
            options={
                'verbose_name': 'BUG原始信息',
                'verbose_name_plural': 'BUG原始信息',
                'db_table': 'tbl_zentao_bug',
            },
        ),
    ]
