# Generated by Django 3.2.14 on 2022-10-18 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zentao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='bug_id',
            field=models.IntegerField(help_text='缺陷id', verbose_name='缺陷id'),
        ),
        migrations.AlterField(
            model_name='bug_status',
            name='severity_four',
            field=models.IntegerField(help_text='严重等级-四级', verbose_name='严重等级-四级'),
        ),
        migrations.AlterField(
            model_name='bug_status',
            name='severity_one',
            field=models.IntegerField(help_text='严重等级-一级', verbose_name='严重等级-一级'),
        ),
        migrations.AlterField(
            model_name='bug_status',
            name='severity_three',
            field=models.IntegerField(help_text='严重等级-三级', verbose_name='严重等级-三级'),
        ),
        migrations.AlterField(
            model_name='bug_status',
            name='severity_two',
            field=models.IntegerField(help_text='严重等级-二级', verbose_name='严重等级-二级'),
        ),
    ]
