# Generated by Django 3.2.14 on 2023-02-07 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zentao', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bugpersonnelconfig',
            table='zentao_personnel_spell',
        ),
    ]
