# Generated by Django 3.2.14 on 2022-12-23 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zentao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bugpersonnelconfig',
            name='phone',
            field=models.CharField(help_text='手机号', max_length=50, verbose_name='手机号'),
        ),
    ]
