# Generated by Django 3.2.14 on 2023-02-07 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zentao', '0002_alter_bugpersonnelconfig_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bugpersonnelconfig',
            name='id',
        ),
        migrations.AlterField(
            model_name='bugpersonnelconfig',
            name='spell',
            field=models.CharField(help_text='拼音', max_length=50, primary_key=True, serialize=False, verbose_name='拼音'),
        ),
    ]
