# Generated by Django 3.2.14 on 2022-10-18 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zentao', '0002_auto_20221018_1414'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bug_Personnel_config',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now_add=True, help_text='更新时间', verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, help_text='逻辑删除', verbose_name='逻辑删除')),
                ('id', models.AutoField(help_text='ID主键', primary_key=True, serialize=False, verbose_name='ID主键')),
                ('spell', models.CharField(help_text='拼音', max_length=50, verbose_name='拼音')),
                ('name', models.CharField(help_text='姓名', max_length=50, verbose_name='姓名')),
                ('phone', models.IntegerField(help_text='手机号', verbose_name='手机号')),
            ],
            options={
                'verbose_name': 'BUG状态信息',
                'verbose_name_plural': 'BUG状态信息',
                'db_table': 'Bug_Personnel_config',
            },
        ),
        migrations.CreateModel(
            name='Bug_Project_config',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now_add=True, help_text='更新时间', verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, help_text='逻辑删除', verbose_name='逻辑删除')),
                ('project_id', models.CharField(help_text='项目ID', max_length=50, primary_key=True, serialize=False, verbose_name='项目ID')),
                ('project_name', models.CharField(help_text='项目名称', max_length=100, verbose_name='项目名称')),
                ('qywx_webhook', models.CharField(help_text='企业微信webhook推送地址', max_length=500, verbose_name='企业微信webhook推送地址')),
                ('status', models.CharField(help_text='推送状态', max_length=10, verbose_name='是否推送状态')),
            ],
            options={
                'verbose_name': 'bug推送配置',
                'verbose_name_plural': 'bug推送配置',
                'db_table': 'bug_config',
            },
        ),
        migrations.RemoveField(
            model_name='bug_status',
            name='project_name',
        ),
        migrations.AlterField(
            model_name='bug',
            name='id',
            field=models.AutoField(help_text='ID主键', primary_key=True, serialize=False, verbose_name='ID主键'),
        ),
        migrations.AlterField(
            model_name='bug',
            name='project_id',
            field=models.ForeignKey(help_text='所属项目ID', on_delete=django.db.models.deletion.CASCADE, to='zentao.bug_project_config', verbose_name='所属项目ID'),
        ),
        migrations.AlterField(
            model_name='bug_status',
            name='project_id',
            field=models.ForeignKey(help_text='所属项目ID', on_delete=django.db.models.deletion.CASCADE, to='zentao.bug_project_config', verbose_name='所属项目ID'),
        ),
    ]
