# Generated by Django 3.2.14 on 2023-02-08 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zentao', '0002_alter_bugpersonnelconfig_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatGPT',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now_add=True, help_text='更新时间', verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, help_text='逻辑删除', verbose_name='逻辑删除')),
                ('id', models.AutoField(help_text='id主键', primary_key=True, serialize=False, verbose_name='id主键')),
                ('question', models.CharField(help_text='问题', max_length=50, verbose_name='问题')),
                ('answer', models.CharField(help_text='答案', max_length=50, verbose_name='答案')),
            ],
            options={
                'verbose_name': 'chatgpt',
                'verbose_name_plural': 'chatgpt',
                'db_table': 'chatgpt',
            },
        ),
        migrations.RemoveField(
            model_name='bugpersonnelconfig',
            name='id',
        ),
        migrations.AlterField(
            model_name='bugpersonnelconfig',
            name='spell',
            field=models.CharField(help_text='拼音', max_length=50, primary_key=True, serialize=False, verbose_name='拼音'),
        ),
    ]
