# Generated by Django 3.2.14 on 2022-10-18 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zentao', '0003_auto_20221018_1724'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zentao_user_config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now_add=True, help_text='更新时间', verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, help_text='逻辑删除', verbose_name='逻辑删除')),
                ('account', models.CharField(help_text='账号', max_length=50, verbose_name='账号')),
                ('password', models.CharField(help_text='密码', max_length=50, verbose_name='密码')),
            ],
            options={
                'verbose_name': '公共字段表',
                'db_table': 'BaseModel',
                'abstract': False,
            },
        ),
    ]
