# Generated by Django 3.2.14 on 2022-10-18 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zentao', '0004_zentao_user_config'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='zentao_user_config',
            options={'verbose_name': 'bug推送配置', 'verbose_name_plural': 'bug推送配置'},
        ),
        migrations.AlterModelTable(
            name='bug_personnel_config',
            table='tbl_bug_personnel_config',
        ),
        migrations.AlterModelTable(
            name='bug_project_config',
            table='tbl_bug_config',
        ),
        migrations.AlterModelTable(
            name='zentao_user_config',
            table='tbl_zentao_user_config',
        ),
    ]
