# Generated by Django 3.2.14 on 2022-10-18 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zentao', '0005_auto_20221018_2239'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='zentao_user_config',
            options={'verbose_name': '禅道用户配置信息', 'verbose_name_plural': '禅道用户配置信息'},
        ),
    ]
